### ISSUE TITLE
`womanTemplate` is importing from the wrong lists

### ISSUE THREAD

**Issue by JohnAlexINL** [JohnAlexCO/gender#2]
In `templates/generic.h` on [line 17](https://github.com/JohnAlexCO/gender/blob/main/templates/generic.h#L17), accidentally using the wrong nameflags.

**Comment by JohnAlexCO** [comment]
https://github.com/JohnAlexCO/gender/commit/1b8975cfd246294a3e659fd021c71c64ae7b521e

**Comment by JohnAlexINL** [comment]
https://github.com/JohnAlexCO/gender/commit/1b8975cfd246294a3e659fd021c71c64ae7b521e
